### ISSUE TITLE
Improve onboarding documentation

### ISSUE THREAD

**Issue by dorzey** [sqlfluff/vscode-sqlfluff#10]
Provide walkthrough of how to configure the extension and consume the output.

**Comment by emekdahl** [comment]
+1

**Comment by dorzey** [comment]
@emekdahl it would be great to know what you feel was missing.

**Comment by emekdahl** [comment]
@dorzey - I was referring to this slack thread where settings.json was manually edited: https://sqlfluff.slack.com/archives/C01GPHR8J0G/p1607715833026600?thread_ts=1607713427.026200&cid=C01GPHR8J0G

**Comment by emekdahl** [comment]
@dorzey is it possible for me to make a PR? If not, I summarized the conversation in slack below in the hopes that it would help others and also reduce the burden on you to provide support on slack.

```
## Configuration

The extension expects sqlfluff to be installed and already added to the path. If it is installed but cannot be found, add the path to your preferences as seen below. Find the path by typing `which sqlfluff` into your terminal.

Edit your VS Code `settings.json` file either through the UI or manually updating the file. The gif below shows the UI path.

![plugin configuration](./media/config.gif)

If you want to manually update the `settings.json` file, open the VS Code command palette and type in `settings.json`. Select `Preferences: Open Settings`. Then, add the following two lines to `settings.json`.

```
"sql.linter.executablePath": "<PATH_TO_YOUR_SQLFLUFF_FROM_WHICH_SQLFLUFF_COMMAND",
"sql.linter.run": "onType"
```

By default the linter will lint on the fly `"sql.linter.run": "onType"` but can be changed to linting as you save `"sql.linter.run": "onSave"`. Note that linting on save is most useful when auto-save is on.
```

**Comment by dorzey** [comment]
@emekdahl sure! 

You should be able to configure those settings via the UI; I've been using VSCode for a while and I've never had to edit the settings.json file; so I think it just needs framing appropriately.

**Comment by aaronsteers** [comment]
For context: 

![image](https://user-images.githubusercontent.com/18150651/102269463-84152f80-3ed1-11eb-9346-41c43629e6cc.png)

**Comment by aaronsteers** [comment]
This is pretty good, I think: 

![Uploading image.png…]()

**Comment by emekdahl** [comment]
@dorzey it sounds like you're content with the current state. I'll look for other ways to contribute.

**Comment by dorzey** [comment]
@emekdahl apologies, that totally wasn't my intent!

I can't possibly be the arbiter of what people find useful. For sure, if you found it useful then other people will too. Please submit a PR!
