### ISSUE TITLE
Typo in the description of sqlfluff.executablePath

### ISSUE THREAD

**Issue by JurjenKnarren** [sqlfluff/vscode-sqlfluff#100]
There is a typo in the description of sqlfluff.executablePath.
Instead of "**executable**", "**exectuable**" is currently used.

See [package.json, line 95](https://github.com/sqlfluff/vscode-sqlfluff/blob/6ca8008f3a96c327b741c6bfdc3b127a3995a4b7/package.json#L95):
`"description": "Points to the sqlfluff exectuable."`

**Comment by RobertOstermann** [comment]
Fixed in v2.3.2
