### ISSUE TITLE
Feature: add support for `.env` files

### ISSUE THREAD

**Issue by natterstefan** [sqlfluff/vscode-sqlfluff#101]
Hi everybody.

First of all, thanks for creating this extension. It is super helpful. One feature request I have and want to request is to add support for providing a path to a `.env` file in the `sqlfluff` settings.

Similar to

```json
"sqlfluff.environmentVariables": [
	{
		"key": "EXAMPLE_KEY",
		"value": "example_value"
	}
],
```

It'd be great if we could add the following:

```json
"sqlfluff.useDotEnvFile": true,
"sqlfluff.customDotEnvFiles": [
	"foo/.env",
	"bar/.env",
],
```

- `sqlfluff.useDotEnvFile`: loads `.env` from the working directory.
- `sqlfluff.customDotEnvFiles`: load other .env files from a different path.

What do you think? It'd be useful if multiple environment variables were also used in other places of the repo where `sqlfluff` is used.

Thanks for your time. 👋 

## Related Comments

- https://github.com/sqlfluff/vscode-sqlfluff/issues/74#issuecomment-1319166775: mentions that the extension uses existing `process.env` variables, but the `.env` is not loaded automatically.

**Comment by RobertOstermann** [comment]
@natterstefan I have added the settings `sqlfluff.env.useDotEnvFile` and `sqlfluff.env.customDotEnvFiles` in v2.3.3, which has been recently published. Could you give that version a try and let me know if these settings work as expected?
