### ISSUE TITLE
Please can you add some documentation / info in the readme on how to configure rules in vscode settings.json

### ISSUE THREAD

**Issue by hblauth** [sqlfluff/vscode-sqlfluff#102]
I want to set the rule "layout.commas" to "leading", and I have tried setting it in "sqlfluff.rules", in "sqlfluff.env.environmentVariables", "sqlfluff.linter.arguments" and    "sqlfluff.format.arguments" but to no avail. Please help!

**Comment by RobertOstermann** [comment]
@hblauth You will have to set up a configuration file for your project. Once you've done that, the file might be picked up and used automatically by this extension, but if not you can set the location of the configuration file using the `"sqlfluff.config"` setting.

https://docs.sqlfluff.com/en/stable/configuration.html

The `"sqlfluff.rules"` setting corresponds to https://docs.sqlfluff.com/en/stable/cli.html#cmdoption-sqlfluff-fix-r and is meant to allow users to only enable certain rules. It does not allow for changing the setup of rules.
