### ISSUE TITLE
vscode not recognizing local config file

### ISSUE THREAD

**Issue by jullianrodriguez** [sqlfluff/vscode-sqlfluff#103]
Hi, I've gone through the process of setting up sqlfluff on my local machine, have gone through the appropriate documentation, and it is able to lint and whatnot, but I can't get it to utilize the local config file on my machine. Relevant info:

macOS Ventura 13.3.1
vscode: 1.78.2
sqlfluff (on my computer): 2.1.1
sqlfluff (VSCode Extension): 2.3.3
Python 3.10.9

Changes made in the sqlfluff VSCode Extension settings:
Dialect: `snowflake`
Executable path: `/Users/<user_name>/anaconda3/bin/sqlfluff`

I've both filled in the section for the config location and also left it blank and haven't been able to get either to work. The initial location I put in was `/Users/<user_name>/.sqlfluff` as that's where the config file is located.

If I check Ignore Local Config, then the linting errors appear in my code window. If I leave it unchecked, nothing happens in my code window. Any help in getting this figured out is much appreciated. Also, apologies if the fix is something really simple that I just missed.

see below for my config file info:
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = None
exclude_rules = L009,L019,L029,L031,L034,L054
recurse = 0
output_line_length = 160
runaway_limit = 10
ignore_templated_areas = True
warnings = L011
encoding = autodetect
max_line_length = 160
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indent_unit = space
tab_space_size = 4
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater]
unwrap_wrapped_queries = True

[sqlfluff:templater:jinja]
apply_dbt_builtins = True

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_source = {% macro source(source_name, table) %}{{source_name}}_{{table}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}
dbt_var = {% macro var(variable) %}item{% endmacro %}
dbt_is_incremental = {% macro is_incremental() %}True{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent
unquoted_identifiers_policy = all

[sqlfluff:layout:type:comma]
line_position = trailing

# Some rules have their own specific config.
[sqlfluff:rules:L003]
lint_templated_tokens = True

[sqlfluff:rules:L007]  # Keywords
operator_new_lines = after

[sqlfluff:rules:L010]  # Keywords
capitalisation_policy = consistent

[sqlfluff:rules:L014]  # Unquoted identifiers
extended_capitalisation_policy = consistent
unquoted_identifiers_policy = column_aliases

[sqlfluff:rules:L016]
ignore_comment_lines = False

[sqlfluff:rules:L029]  # Keyword identifiers
unquoted_identifiers_policy = aliases

[sqlfluff:rules:L030]  # Function names
capitalisation_policy = consistent

[sqlfluff:rules:L038]
select_clause_trailing_comma = forbid

[sqlfluff:rules:L040]  # Null & Boolean Literals
capitalisation_policy = consistent

[sqlfluff:rules:L042]
# By default, allow subqueries in from clauses, but not join clauses.
forbid_subquery_in = join

[sqlfluff:rules:L047]  # Consistent syntax to count all rows
prefer_count_1 = False
prefer_count_0 = False

[sqlfluff:rules:L057]
allow_space_in_identifier = True
```

**Comment by RobertOstermann** [comment]
@jullianrodriguez What do you get in the sqlfluff output channel? When I tried using your configuration file I was given an error. I think your configuration file is outdated and might not work with sqlfluff v2.1.1

![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/46828475/73952a36-17a0-477b-9361-c58eeac0d24a)

**Comment by RobertOstermann** [comment]
I wish I could be more help, but I don't know much about most of the individual rules. You would have to try to find it in the [documentation ](https://docs.sqlfluff.com/en/stable/) or checkout the [sqlfluff repository](https://github.com/sqlfluff/sqlfluff) and create an issue there.
