### ISSUE TITLE
Error message inserted in source sql file when trying to format its content

### ISSUE THREAD

**Issue by rubensa** [sqlfluff/vscode-sqlfluff#106]
Create a **test.sql** file like:
```sql
SET MODE LEGACY; -- noqa: PRS
```

Save it.

The content of the file is updated with:
```sql
  [0 templating/parsing errors remaining after "ignore" & "warning"]
SET MODE LEGACY; -- noqa: PRS
```

In the SQLFluff output I can see:
```bash
------------------------------------------------------------

Format triggered for /workspaces/test-app/src/test/resources/test.sql

------------------------------------------------------------

Reading from stdin, not file, input may be dirty/partial

--------------------Executing Command--------------------

/opt/conda/envs/dev/bin/sqlfluff fix --force --dialect snowflake --exclude-rules RF01,RF01 -

------------------------------------------------------------

Received close event, code 0 signal null
Raw stdout output:

------------------------------------------------------------

  [0 templating/parsing errors remaining after "ignore" & "warning"]
SET MODE LEGACY; -- noqa: PRS


------------------------------------------------------------

Raw stderr output:

------------------------------------------------------------

  [1 templating/parsing errors found]


------------------------------------------------------------


------------------------------------------------------------

Reading from file, not stdin

--------------------Executing Command--------------------

/opt/conda/envs/dev/bin/sqlfluff lint --format json --dialect snowflake --exclude-rules RF01,RF01 src/test/resources/test.sql

------------------------------------------------------------

Received close event, code 1 signal null
Raw stdout output:

------------------------------------------------------------

[{"filepath": "src/test/resources/test.sql", "violations": [{"line_no": 1, "line_pos": 1, "code": "LT01", "description": "Expected only single space before start square bracket '['. Found '  '.", "name": "layout.spacing"}, {"line_no": 1, "line_pos": 1, "code": "LT02", "description": "First line should not be indented.", "name": "layout.indent"}, {"line_no": 1, "line_pos": 1, "code": "LT13", "description": "Files must not begin with newlines or whitespace.", "name": "layout.start_of_file"}, {"line_no": 1, "line_pos": 3, "code": "PRS", "description": "Line 1, Position 3: Found unparsable section: '[0 templating/parsing errors remaining a...'", "name": ""}]}]

------------------------------------------------------------
```

Looks like the `-- noqa: PRS` might not be taken into account for the `SET MODE LEGACY; -- noqa: PRS` line (or other error might be detected after that but should not, cause there is no more content in the file), which generates an output including the error message `[0 templating/parsing errors remaining after "ignore" & "warning"]` that is updated in VSCode editor and re-evaluated which generates the error message `[1 templating/parsing errors found]`.

_PS_:  The same happens if only `-- noqa` (without` : PRS`) is used

**Comment by rubensa** [comment]
sqlfluff, version 2.1.2
vscode-sqlfluff, version 2.3.4

**Comment by RobertOstermann** [comment]
@rubensa Thanks for including the sqlfluff output channel details, makes it much easier for me to debug. Looks like this is a bug with the extension, I will update it to ignore that message. Hopefully will have that update out within a few days.

**Comment by RobertOstermann** [comment]
@rubensa This should be sort-of fixed in v2.3.5. Unfortunately SQLFluff does not format the file if there are parsing errors, even if those errors are ignored. So the best I could do was show an error message if this happens and ensure the file does not get changed.

**Comment by rubensa** [comment]
Ouch! Sorry to know that. 
Any way, thanks for the effort. 
Any chance for automatic "partial formatting"?
Now that [format selection](https://github.com/sqlfluff/vscode-sqlfluff/issues/94#issuecomment-1636655726) is supported, what about automatically selecting the parts without `-- noqa`, formatting then and putting them back with the ones containing the `-- noqa`? Do you think that might be possible?

**Comment by RobertOstermann** [comment]
@rubensa That might be possible. But probably not something I would implement, I think people could just use "Format Selection" on their own. Determining the ranges without parsing errors might be a bit difficult. Perhaps this would be a good issue to create in the main sqlfluff repo.
