### ISSUE TITLE
getting error on onsave action

### ISSUE THREAD

**Issue by AshutoshSajan** [sqlfluff/vscode-sqlfluff#108]
first i was getting this error 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version! warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported " Traceback (most recent call last): File "/home/user/.local/bin/sqlfluff", line 8, in

then i updated the requests, urllib3, chardet packages and now i am getting this error

raceback (most recent call last): File "/home/user/.local/bin/sqlfluff", line 8, in <module> sys.exit(cli()) File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__ return self.main(*args, **kwargs) File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1053, in main rv = self.invoke(ctx) File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/user/.local/lib/python3.8/site-packages/click/core.py", line 754, in invoke return __callback(*args, **kwargs) File "/home/user/.local/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 605, in lint config = get_config( File "/home/user/.local/lib/python3.8/site-packages/sqlfluff/cli/commands.py", line 418, i...

i am using ubuntu 20.04

**Comment by RobertOstermann** [comment]
Are you able to run sqlfluff from the terminal? You can check the output channel to see the exact sqlfluff command this extension is running and re-run that in the terminal.

**Comment by AshutoshSajan** [comment]
yes it's working, i got the error in output logs, it was due to empty .sqlfluff file. we can close the issue i guess, thanks @RobertOstermann
