### ISSUE TITLE
Doesn't seem to pick up settings in my .sqlfluff settings

### ISSUE THREAD

**Issue by dorzey** [sqlfluff/vscode-sqlfluff#11]
Unrelated (but related): One thing that I noticed in the past is that the extension doesn't seem to pick up settings in my `.sqlfluff` settings file saved to the root of my repo. Not a change per se from prior versions, but I would love to see if we/I can debug this so I can override the default formatting and apply my team's agreed-upon format rules.

_Originally posted by @aaronsteers in https://github.com/sqlfluff/vscode-sqlfluff/issues/9#issuecomment-739437293_

**Comment by aaronsteers** [comment]
If this was an issue, I think it is now resolved.

The following test was successful:

1. Open `.sqlfluff` (in the root of the repo) and change `sqlfluff:rules.tab_space_size` from `4` to `2`.
2. Run VS Code `Format Document` on an open sql file, and observe that the tab indents are all auto-updated to 2 spaces. ✅
3. Revert to `tab_space_size` = `4`, rerun `Format Document`, and confirm all tab indents are reverted back to 4 spaces. ✅

**Comment by aaronsteers** [comment]
Since the issue appears resolved, I'd be in favor of closing this. We can re-open or create a new issue if it appears to be a problem in the future.
