### ISSUE TITLE
Feature Request / Question: `noqa` inline quick fix 

### ISSUE THREAD

**Issue by pep-sanwer** [sqlfluff/vscode-sqlfluff#112]
Hello! A quick question on existing features / possible future feature:

I currently only see the option to exclude rules from the workspace or global settings using the quick fix tooltip:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/112018564/e0d170f7-c522-4e0c-8d12-d1c331f2d4c6)

Is there a feature currently to have an inline quick fix option like the below (from the `ruff` extension)?:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/112018564/8fd2f80f-9a81-41bf-8699-63d0e86d8950)
Which results in:
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/112018564/b2279fd7-6819-4628-bb66-c4ff71125ea6)

If not, this would a terribly useful quick fix action to have.

Appreciative of this lovely tool!

**Comment by RobertOstermann** [comment]
Which version of the extension are you on? I believe there should be options to ignore the individual rule for that line or to ignore all rules for that line.

**Comment by RobertOstermann** [comment]
Hmm, it is working for me on that version. Do you have `sqlfluff.codeActions.noqa` set in your settings.json? If that is false (it is not false by default) then the code actions will not show.

**Comment by RobertOstermann** [comment]
@pep-sanwer  Actually taking a look at it, that `ST06` rule is excluded from the noqa by default. Don't remember exactly why, but you can set `sqlfluff.codeActions.noqa: true` to enable the code actions for all the rules, the ones set in the array by default do not show code actions for those rules.
