### ISSUE TITLE
dbt project not registered

### ISSUE THREAD

**Issue by connor-mcshane** [sqlfluff/vscode-sqlfluff#114]
Howdy folks, I keep getting this error `dbt project not registered` for some reaason and I don't know why. 

Does anyone know what it means?

![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/10451364/c99de03e-b750-4927-83b6-3af251e31f68)

Something to do with health checks failing but I am not sure.

**Comment by noel** [comment]
Are you using the latest version and have this disabled?

![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/19945/1574c92f-7bc7-4e39-99ee-23b348adc9af)

**Comment by connor-mcshane** [comment]
Ahh okay great fixed thanks <3
