### ISSUE TITLE
`sqlfluff 3.0` release breaks extension `sql` document formatter

### ISSUE THREAD

**Issue by pep-sanwer** [sqlfluff/vscode-sqlfluff#126]
After upgrade to `sqlfulff 3.0`, I am seeing the following behavior with Settings: `Sqlfluff > Format: Enabled` set to true:

The line:
```
The -f/--force option is deprecated as it is now the default behaviour.
``` 
is inserted at the top of the file on format.

Based on the extension documentation I am assuming this is a consequence of the extension utilizing `sqlfluff fix --force <path>` on format, where `--force` is deprecated as of `sqlfulff 3.0`

**Comment by RobertOstermann** [comment]
@pep-sanwer @levelupatlas-mat I have released v3.0.0, which should fix this issue
