### ISSUE TITLE
Add VS Code Extensions search optimization for "DBT" keyword

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/vscode-sqlfluff#13]
@dorzey - I love what we can do now with this extension - especially with the upcoming VS Code formatter support (again **_thank you!_** for that) and I want to help get the word out. One thing I noticed is that this doesn't show up in a search for "DBT" and I think it should - not that it is exclusively for dbt but so much of the community and even the evolution of the sqlfluff product has been for DBT use cases.

Do you have any thoughts on this? I know exactly zero about what control we have over surfacing results in the VS Code extensions view, but from my perhaps naïve perspective, I would be supportive of one or more of the below:

1. Extending the short text description to include "DBT".
     - from `An extension to use the sqlfluff linter in vscode` 
     - to something like `A VS Code linter and auto-formatter for sqlfluff, a popular and powerful linting tool for SQL and DBT.`
2. Extending the README.md description (assuming this also helps it appear in dbt search results.)
      - possibly add something in the readme like 
      - to something like 
          > SQLFluff also has first-class support for jinja2 templating, including support for DBT templating.

However you would want to present it, I think it's worth pitching the power of SQLFluff and its compatibility with DBT. 

Here's what currently shows on a search for `dbt`:

![image](https://user-images.githubusercontent.com/18150651/102026075-c7946000-3d50-11eb-9354-312c49282276.png)

The DBT formatter that shows there in the list is not nearly as powerful or customizable as SQLFluff. While it was probably the first offering out there, it has its own issues and I wouldn't necessarily recommend that formatter for my teams.

Part of goal with logging this issue is to make sure new and existing DBT users know they have this extension as a better option (IMHO) for their DBT projects.

**Comment by dorzey** [comment]
Thanks! 

You've also made me realise that I haven't set any "tags" for the extension; I think they help searching too.
