### ISSUE TITLE
OSError: [Errno 6] Device not configured: '/dev/tty'

### ISSUE THREAD

**Issue by Jacques-Peeters** [sqlfluff/vscode-sqlfluff#130]
# Problem 

Upgrading to VSCode extension `v3.0.0` lead to the following bug when I try to format code

`OSError: [Errno 6] Device not configured: '/dev/tty'`

```
pip freeze | grep sqlfluff
sqlfluff==2.3.5
sqlfluff-templater-dbt==2.3.5
```

I suspect version 3.0.0 is not backward compatible with a SQLFLUFF<3.0 

# Current solution

Downgrade extension to `v2.4.4`

**Comment by ericdmontu** [comment]
Same here, thanks for the current solution, roll back to v2.4.4 does work.

**Comment by keraion** [comment]
@Jacques-Peeters @ericdmontu does adding the "--force" argument to the format arguments in settings.json fix this?

```json
    "sqlfluff.format.arguments": [
        "--force"
    ]
```

**Comment by BubbaTLC** [comment]
@keraion Adding the force argument worked for me.

**Comment by Jacques-Peeters** [comment]
Closing as it did work 👍
