### ISSUE TITLE
No documentation or examples for how to override defaults for rules or rule groups

### ISSUE THREAD

**Issue by cvbriggler** [sqlfluff/vscode-sqlfluff#131]
I need to set the capitalisation.keywords rule so that the capitalisation_policy is "upper". This will enforce a rule that keywords are in upper case.

There is no documentation for how to do this in settings.json file. I'm assuming it is in the "sqlfluff.rules": [] section of settings.json. I need to know how to enter json to get the desired behavior.

Please update your documentation to include guidance on how to configure specific rules.

**Comment by RobertOstermann** [comment]
@cvbriggler it is not possible to set that in settings.json. you will have to create a .sqlfluff configuration file to configure specific rules. There is more information about sqlfluff config files on the sqlfluff website

**Comment by cvbriggler** [comment]
Thanks Robert. I'll take that track. We can close this issue.
