### ISSUE TITLE
[Feature] Show rule name in `Problems` tab

### ISSUE THREAD

**Issue by aleix-cd** [sqlfluff/vscode-sqlfluff#134]
### Is there an existing issue for this?
No

### Describe the issue
When linting errors pop up in the `Problems` tab in VSCode, only the rule code is returned.

E.g.
`Expected indent of 4 spaces. sqlfluff(LT02) [Ln 83, Col 1]`

### Relevant screenshot
<img width="1058" alt="image" src="https://github.com/sqlfluff/vscode-sqlfluff/assets/97022738/0b85f45b-98a2-4339-81a3-1394f39c1714">

### Expected behaviour
Since we can now use the rule name in our `noqa` comments to disable rules (e.g. `noqa: disable=layout.indent`), it would be much easier to show the rule name in the `Problems` tab as well. 

Example of how the Problems output could look like:
`Expected indent of 4 spaces. sqlfluff(LT02: layout.indent) [Ln 83, Col 1]`

### Are you willing to open a PR to help address this issue?
Yes, but I'd probably need assistance

**Comment by RobertOstermann** [comment]
@aleix-cd This should be updated in v3.1.1

**Comment by aleix-cd** [comment]
Just tested it, wonderful! Thanks a lot ❤️
