### ISSUE TITLE
VSCode option to specify ignores

### ISSUE THREAD

**Issue by jleacox** [sqlfluff/vscode-sqlfluff#15]
I thought it might be nice to be able to specify ignores (e.g. parsing errors) in the VSCode problem highlighting, similar to in the CLI.

**Comment by aaronsteers** [comment]
@UnityIndigo - Do you have a `.sqlfluff` or similar config file in your repo? This config format allows you to specify the applicable rules to include or ignore, and also allows you to confirm some rule-specific settings.

For example, we are using the following config in our project:

`{root}/.sqlfluff`:

```ini
[sqlfluff]
verbose = 0
nocolor = False
dialect = snowflake
templater = jinja
rules = L001,L002,L003,L004,L005,L006,L007,L008,L009,L010,L011,L012,L013,L014,L015,L016,L017,L018,L019,L020,L021,L022,L023,L024,L025,L026,L027,L028,L029,L030
exclude_rules = None
output_line_length = 90

[sqlfluff:indentation]
indented_joins = False

# [sqlfluff:templater:jinja]
# apply_dbt_builtins = True

[sqlfluff:rules]
tab_space_size = 4
max_line_length = 92
indent_unit = space

# keyword capitalization
[sqlfluff:rules:L010]
capitalisation_policy = upper

# non-keyword capitalization
[sqlfluff:rules:L014]
capitalisation_policy = lower

[sqlfluff:rules:L019]
comma_style = trailing

[sqlfluff:rules:L028]
single_table_references = consistent

# function capitalization
[sqlfluff:rules:L030]
capitalisation_policy = upper
```

**Comment by dorzey** [comment]
Maybe I'm misunderstanding, but I thought @UnityIndigo was suggesting something equivalent to `sqlfluff fix –ignore parsing`.

**Comment by UnityIndigo** [comment]
> Maybe I'm misunderstanding, but I thought @UnityIndigo was suggesting something equivalent to `sqlfluff fix –ignore parsing`.

Yes, wasn't there just an issue raised where the .sqlfluff config file wasn't being used in VSCode?

**Comment by aaronsteers** [comment]
Yes, sorry. Looks like I may have misread. Since I'm not familiar with the `-ignore parsing` option, I think I read this as excluding specific rules. I don't know if that option is able to be specified in the config file, and if not, please disregard my last. 😄

**Comment by aaronsteers** [comment]
> Yes, wasn't there just an issue raised where the .sqlfluff config file wasn't being used in VSCode?

That was me, and after further testing, I was not able to reproduce it. We just closed that issue.

**Comment by dorzey** [comment]
Should we always `-ignore parsing`? Or make it a configurable option?

**Comment by aaronsteers** [comment]
Personally, I think configurable is nice. In theory, at least, I like seeing the red squiglies when I've got some obvious parsing error. I'll have to read up on this more though to see if I'm not missing something.

**Comment by dorzey** [comment]
@UnityIndigo in the interim you should be able to add the following to your `.sqlfluff` config file
```
[sqlfluff]
ignore=parsing
```

**Comment by RobertOstermann** [comment]
You can now ignore parsing errors in v0.0.6
