### ISSUE TITLE
Silence notification when file/path is in `.sqlfluffignore`

### ISSUE THREAD

**Issue by mroy-seedbox** [sqlfluff/vscode-sqlfluff#155]
When the extension is configured to run automatically upon saving a file, and that file/path is in `.sqlfluffignore`, it keeps showing this notification:
![image](https://github.com/user-attachments/assets/c7cd5f2c-4205-4d8f-a762-1ed7aa398433)

Would it be possible to add a toggle to disable this notification? We know that the file shouldn't get linted, but the extension tries to do it anyway. 🤷‍♂️ 

And thank you for the amazing extension! 🙏 💙

**Comment by RobertOstermann** [comment]
Does adding the argument to your extension setup in settings.json disable the notification? `"sqlfluff.linter.arguments": ["--disregard-sqlfluffignores"]`. You might have to add that to the format arguments as well if you are trying to format it.

You could also try disabling the notification popups with `"sqlfluff.suppressNotifications": true`

**Comment by mroy-seedbox** [comment]
Yeah.... I was hoping to:
- Not ignore `.sqlfluffignore`.
- Not disable _**all**_ notifications.

It's really this specific notification which doesn't bring much value. If the extension took `.sqlfluffignore` into consideration before running, then it wouldn't even trigger for those files. But since it triggers on every `.sql` file when it's saved... we end up here.

I'll try your recommendation of `"sqlfluff.linter.arguments": ["--disregard-sqlfluffignores"]` for now. At least that will get rid of the notification, but now these files will be full of errors (since they shouldn't be linted in the first place). 😞

**Comment by RobertOstermann** [comment]
What version of the extension are you on? I think that error message has been hidden in the current version of the extension, but not sure about the 2.x versions of the extension.

**Comment by mroy-seedbox** [comment]
I'm on `v3.2.0`. It's set to auto update.

**Comment by RobertOstermann** [comment]
Hmm, looks like they changed the message, you must be on a later sqlfluff version than I am. I just published v3.2.1 which should hide that error message.

**Comment by mroy-seedbox** [comment]
It works! 🎉 🍾 🚀 

Thank you!! 🙏 🙌 

And you did it so quick! 🏎️ 💪  💙
