### ISSUE TITLE
Give all settings appropriate scopes, so that they work in multi-root workspaces

### ISSUE THREAD

**Issue by quodlibetor** [sqlfluff/vscode-sqlfluff#156]
Currently no sqlfluff settings have scopes defined. I'm not sure what the default is, but when I create a multi-root workspace the sqlfluff settings no longer apply.

This makes sense, as the [workspace settings docs](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings) say:

> To avoid setting collisions, only resource (file, folder) settings are applied when using a multi-root workspace.

From [the extension docs](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) there are a lot of possible scopes, but in particular:

> scope
> 
> A configuration setting can have one of the following possible scopes:
> 
> - ... snip ...
> - resource - Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.

I believe that all sqlfluff settings could be resource settings but I'm not sure. Changing this seems straightforward, for example (from [current package.json](https://github.com/sqlfluff/vscode-sqlfluff/blob/963aa6e952cc1f152baa6c577de05afb289a4f66/package.json#L76-L82))

```jsonc
  "configuration": {
      "properties": {
        "sqlfluff.config": {
          "type": "string",
		  "scope": "resource",  // <-- new
          "default": "",
          "description": "Specify an additional configuration file that overrides the standard configuration files."
        },
```

**Comment by RobertOstermann** [comment]
@quodlibetor I'm think the default scope is "window", will changing the scope to "resource" create any issues? I'm not very familiar with scopes.

**Comment by quodlibetor** [comment]
I'm not confident, I've never done any VSCode extension development.

Intuitively, though, all of the settings that I can see _should_ be editable on a per-directory level -- none of them affect the VSCode window itself, just how sqlfluff itself is executed.

**Comment by RobertOstermann** [comment]
Makes sense, doesn't seem like this change would hurt anything. Pushing the update in v3.3.0

**Comment by quodlibetor** [comment]
thank you!
