### ISSUE TITLE
sqlfluff.executablePath should not sync

### ISSUE THREAD

**Issue by Snuffy2** [sqlfluff/vscode-sqlfluff#158]
I run VSCode and the sqlfluff plugin on several different computers. I use VSCode setting s sync. Some of these computers are Windows and others are Mac. Additionally, some are corporate computers where my access and ability to install and change settings are limited.

Thus, the install location of sqlfluff is not uniform and cannot always be part of the system path. I can get around this by manually specifying the location of sqlfluff in sqlfluff.executablePath. However, this setting currently syncs accross so every time I go to a different computer with a different location for sqlfluff, I need to change it.

Can you please update the sqlfluff plugin to __not__ sync sqlfluff.executablePath

**Comment by RobertOstermann** [comment]
@Snuffy2 You should be able to use the `"settingsSync.ignoredSettings": ["sqlfluff.executablePath"],` in your settings.json to disable syncing that setting, or any settings you don't want to sync.

**Comment by Snuffy2** [comment]
Thanks, I'll give that a try. I was not aware that this option existed. 

I'd still vote that `sqlfluff.executablePath` be set to not sync but I can follow your suggestion as well.

**Comment by RobertOstermann** [comment]
I think for those that do not want it to sync then this setting is a good alternative. The other option is to set `sqlfluff.executablePath` only in workspace settings. I do not want to change the sync behavior for only this setting as that could confuse and would be unexpected.
