### ISSUE TITLE
Sql fluff garbles correct syntax

### ISSUE THREAD

**Issue by theking2** [sqlfluff/vscode-sqlfluff#162]
After formatting with sqlfluff it turned 

## this

```sql
select 
	CONCAT_WS(
	' ', ITEMNR, report_sales_100.DESCRIPTION
	) as `Artikel Nr.`, 
	PHYSICIAN, 
	BATCHID, 
	INVOICENR, 
	sum(Quantity) / _c.`count` Menge 
from invoice_physician 
join report_sales_100 using(INVOICENR) 
join product_with_family using(ITEMNR) 
join (
	select 
		INVOICENR, 
		count(PHYSICIAN) `count` 
	from 
		invoice_physician 
	group by 
		INVOICENR
) _c using(INVOICENR) 
group by 
	ITEMNR, 
	PHYSICIAN, 
	BATCHID 
order by 
	ITEMNR, 
	PHYSICIAN, 
	BATCHID;
``` 

## into this

```sql
with _C as (
    select
        INVOICENR,
        COUNT(PHYSICIAN) as `count`
    from
        INVOICE_PHYSICIAN
    group by
        INVOICENR
)
select
    PHYSICIAN,
    BATCHID,
    INVOICENR,
    CONCAT_WS(
        ' ', ITEMNR, REPORT_SALES_100.DESCRIPTION
    ) as `Artikel Nr.`,
    SUM(QUANTITY) / _C.`count` as MENGE
from INVOICE_PHYSICIAN
inner join
    REPORT_SALES_100
    on INVOICE_PHYSICIAN.INVOICENR = REPORT_SALES_100.INVOICENR
inner join PRODUCT_WITH_FAMILY using (ITEMNR)
inner join _C using (INVOICENR)
group by
ITEMNR,
PHYSICIAN,
BATCHID
order by
ITEMNR,
PHYSICIAN,
BATCHID;
```

what did I miss?

**Comment by theking2** [comment]
Hmm. I can try if you tell me how to do that....

**Comment by RobertOstermann** [comment]
The Output channel should show you the exact command the extension uses to format the code. It might also tell you if there was an error formatting, which is probably why it is clearing out the code.

![image](https://github.com/user-attachments/assets/b53c8ab4-5b69-4164-8aad-21909373df65)

**Comment by theking2** [comment]
Actually vscode and SQL don't seem to like each other. I've reinstalled sqlfluff but "MS SQL" seems to think the code is not valid at all.
![image](https://github.com/user-attachments/assets/2b68a4bb-9079-4664-83ee-bea67cbd41ae)

**Comment by theking2** [comment]
![image](https://github.com/user-attachments/assets/4cf66069-021d-4840-aab0-9b1340047c00)

**Comment by theking2** [comment]
![image](https://github.com/user-attachments/assets/e313b39f-752f-4850-8cb5-0bed7c204f35)

**Comment by theking2** [comment]
![image](https://github.com/user-attachments/assets/53889221-9bb0-45c1-b433-c3e4ab2bf1ad)

 ok, I'm giving up
