### ISSUE TITLE
How to allow to write a filtration condition in one line with WHERE keyword

### ISSUE THREAD

**Issue by Kirill-Ulich** [sqlfluff/vscode-sqlfluff#163]
I use a construction of this type in many places:
```sql
WHERE 1 = 1
    AND col1 = 'a'
    AND ...
```
This is convenient because I can comment out a line or several lines when debugging and nothing will break.
However, sqlfluff requires moving `1 = 1` to a new line. Is there any way I can configure sqlfluff to allow such constructions?
`Noqa` is not suitable because such a construction is very often used. Ignoring the LT02 rule is also not suitable because other indents issues should not be ignored.

**Comment by RobertOstermann** [comment]
I am not sure, you could ask in the main [sqlfluff](https://github.com/sqlfluff/sqlfluff) repo, they know more about configuration than I do.

**Comment by Kirill-Ulich** [comment]
Okay, thanks
