### ISSUE TITLE
Issue with parameters in latest published version (v0.0.4)

### ISSUE THREAD

**Issue by b-per** [sqlfluff/vscode-sqlfluff#19]
Hi,

The latest version on the marketplace, v0.0,4 has an issue with the parameters. The code is looking at the parameter `linter.executablePath` instead of `sql.linter.executablePath`. So if the command `sqlfluff` is not in the path v0.0.4 doesn't work.

It looks like it is now fixed in master but the fix has not been pushed to a new version in the marketplace yet.

**Comment by dorzey** [comment]
The new version was released. Apologies for the delay.
