### ISSUE TITLE
BUG: The executable was not found. Use the 'sql,jinja-sql.executablePath' ...

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/vscode-sqlfluff#20]
This bug was surfed in the sqlfluff slack:

> Cannot lint /jaffle_shop_mssql/models/staging/stg_orders.sql. The executable was not found. Use the 'sql,jinja-sql.executablePath' setting to configure the location of the executable

Several things are odd here:

1. What kind of config is `sql,jinja-sql.executablePath`?
2. Isn't `sql.linter.executablePath` the relevant config?

I searched around the repo to try and find where `sql,jinja-sql.executablePath` might be raised, but no dice. Help me dorzey!

**Comment by swanderz** [comment]
@nolanbconaway thanks for reporting this for me Happy to provide any more info. The `jinja-sql` thing that showed up was weird! Current theory is somehow the Better Jinja extension is interfering? That's where the `,jinja-sql` piece is coming from...


Mac Os `11.2`
VSCode `1.51.1`
Anaconda `vSomething?`
sqlfluff versions `0.3.6` and `0.4.0.a3 ` (both didn’t work?)
extension `dorzey.vscode-sqlfluff=v0.0.4`  and here’s what i think are my relevant settings in .vscode/settings.json
```
"python.pythonPath": "/Users/anders.swanson/opt/anaconda3/envs/dbt/bin/python",
"sql.linter.executablePath": "/Users/anders.swanson/opt/anaconda3/envs/dbt/bin/sqlfluff",
"sql.linter.run": "onType",
"files.associations": {
  "*.sql": "jinja-sql",
  "*.dbtspec": "yaml"
},
```

**Comment by camfrout** [comment]
This is related to an older version of `lintingProvider.ts` (in [this commit](https://github.com/sqlfluff/vscode-sqlfluff/commit/bc01a5096660612e1883907c322def760dd72959) that is still used in version 0.0.4 of the extension.

The message in the older version was "Cannot lint ${textDocument.fileName}. The executable was not found. Use the '${this.linter.languageId}.executablePath' setting to configure the location of the executable"

The error message is now different in master so the issue should disappear when a new version of the extension is realeased.

**Comment by swanderz** [comment]
glad to know you've got it under control! so if I were to build a vsix from the master branch, might I believe to format on save? Or is there something to the error message that I might need to change?

I don't know why `this.linter.languageId` = `sql,jinja-sql.executablePath`. Is this a problem? Is it because of my `files.associations`?

**Comment by camfrout** [comment]
I just built a new version from master locally and the linter works correctly now, even when providing a path for `sqlfluff`. The formatter doesn't seem to work though.

**Comment by zhongjiajie** [comment]
I come with the same issue, do we have any news here? @nolanbconaway @dorzey

**Comment by nolanbconaway** [comment]
I think this was it! https://github.com/sqlfluff/vscode-sqlfluff/issues/20#issuecomment-782944582

The issue magically vanished for me, probably due to an update. Have you tried updating vscode and/or the plugin?

**Comment by daaain** [comment]
I just installed the plugin and ran into the problem 😿 

Is there any chance someone could please do a 0.0.5 release to get the fix out?

**Comment by b-per** [comment]
I have seen that 0.0.5 is out now, so the extension should be working when using `"sql.linter.executablePath"` in the config.

**Comment by dorzey** [comment]
Sorry; I'm still catching up on the backlog of issues. Could somebody please confirm if this is fixed?
