### ISSUE TITLE
Sqfluff doesn't register as a formatter

### ISSUE THREAD

**Issue by Cabeda** [sqlfluff/vscode-sqlfluff#21]
When I run the command "Format document" it throws the error on the image below

![image](https://user-images.githubusercontent.com/8181056/107668076-2bbb9d80-6c88-11eb-8d30-b9a7d528b495.png)

I'm using the following:

Version: 1.53.1
Commit: 5d424b828ada08e1eb9f95d6cb41120234ef57c7
Date: 2021-02-08T23:35:15.302Z (2 days ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0
sqlfluff: 0.4.0a3

Sqlfluf seems to be working fine but doesn't register as a formatter

**Comment by xmatthias** [comment]
I think this has been fixed with the release of 0.0.5 of this extension and should as such be closed...

**Comment by Cabeda** [comment]
Agree. Closing this as it's not occurring anymore 😄
