### ISSUE TITLE
Linter Does not Respect .sqlfluff Configs / `templater=dbt`

### ISSUE THREAD

**Issue by tnightengale** [sqlfluff/vscode-sqlfluff#27]
Hi,

I can't seem to make the linter respect a `.sqlfluff` file present in my project. The "problems" section is obviously generated using the stock SQLFluff configs: the output does not match at all with the CLI output from running `sqlfluff lint <model_path>`.

I'm not super familiar with Typescript or VS code extensions but I'd be happy to troubleshoot if anyone can show me in the code where the sqlfluff command is being run, (i.e. from where) and how the output is being loaded into a class.

Thanks,

Teghan

**Comment by sbronstein** [comment]
I am having the same issue. I am excluding rules:
![Screen Shot 2021-05-03 at 8 55 10 PM](https://user-images.githubusercontent.com/855177/116950188-44699d00-ac52-11eb-9fd4-0f387a8b9621.png)

Which the VSCode extension is ignoring:
![Screen Shot 2021-05-03 at 8 54 58 PM](https://user-images.githubusercontent.com/855177/116950202-4cc1d800-ac52-11eb-83fd-c89f9dee0a18.png)

**Comment by tnightengale** [comment]
For added context, I am using `templater=dbt` in my configs

**Comment by GClunies** [comment]
Same issue here.

**Comment by juangesino** [comment]
+1 on this, I'm getting the same issue. I have a `. sqlfluff` configuration file in the root directory of my dbt project (`templater = dbt`) that seems to be ignored by the extension.

**Comment by cluedtke** [comment]
+1

Would also be great if we can get this extension to respect [ignoring individual lines inline](https://docs.sqlfluff.com/en/stable/configuration.html#ignoring-individual-lines)!

**Comment by puetsch** [comment]
Related to https://github.com/sqlfluff/vscode-sqlfluff/issues/38

**Comment by RobertOstermann** [comment]
This should be fixed in v0.0.6

**Comment by yingyingqiqi** [comment]
I found that exclude_rules did not work when setting config=.sqlfluff configuration file in vscode-sqlfluff. Below are some troubleshooting methods I have summarized: 
1. Check if vscode-sqlfluff has configured sqlfluff.config. 
2. If there is a default configuration file, please refer to the [documentation](https://docs.sqlfluff.com/en/stable/configuration.html#nesting). If so, set "sqlfluff.ignoreLocalConfig" to true to prevent loading errors.
3. Confirm whether vscode-sqlfluff has configured "sqlfluff.excludeRules": ["TMP", "rules"] or "sqlfluff.codeActions.excludeRules.workspace" or "sqlfluff.codeActions.excludeRules.global". Please set all of them to “sqlfluff.codeActions.excludeRules.workspace”:false or “sqlfluff.excludeRules”: []. (Reason: To prevent running sqlflluf fix while using the parameter --exclude-rules "TMP" --config ./. Sqlfulff, then exclude_rules will only take effect with --exclude-rules TMP).
Hope it's helpful for you.
