### ISSUE TITLE
Support  --exclude-rules --rules argument

### ISSUE THREAD

**Issue by noklam** [sqlfluff/vscode-sqlfluff#35]
Thanks for creating this plugin. Is it possible to add a configuration allows user to only use a subset of rules? (--exclude-rules or --rules)

`sqlfluff fix --exclude-rules L036 file.sql`

**Comment by NiallRees** [comment]
Hey noklam, we have a `--rules` flag to do this. See [here](https://docs.sqlfluff.com/en/stable/cli.html#cmdoption-sqlfluff-fix-rules). Closing for now!

**Comment by RobertOstermann** [comment]
Included in v0.0.6
