### ISSUE TITLE
executablePath seems to have no effect

### ISSUE THREAD

**Issue by itajaja** [sqlfluff/vscode-sqlfluff#39]
i have sqlfluff installed in a virtualenv. I tried setting `sql.linter.executablePath` to the virtualenv location (I am pretty certain is correct) but the extension says "The executable was not found". after installing sqlfluff globally, then the extension works (whether I set `executablePath` or not). this leads me to think that the `executablePath` configuration field is not correctly taken into consideration

**Comment by RobertOstermann** [comment]
Please try v0.0.6 and let me know if the problem is still occurring.
