### ISSUE TITLE
Extension ignores settings, fixed file is marked as unsaved and parses twice, parsed content is pasted into a currently opened tab instead of the original file

### ISSUE THREAD

**Issue by XenorPLxx** [sqlfluff/vscode-sqlfluff#40]
Hi!

I have set my VSCode to save files on focus change.
Extension is set to lint and fix files onSave by default. When I switch tabs, it is pasting the linted content into my new tab instead of the source file it was taken from.

I tried setting the automatic option to 'off', but it is ignored by the extension. Also, when I save the file manually, it's marked as unsaved even after nothing is changed by linter, so switching tabs saves it again and runs linting/fixing again.

Here's a video presenting the problem. Note that I pressed ctrl+z in the settings.json to restore original content (keystrokes not visible on video):

https://user-images.githubusercontent.com/6712823/138454701-b0cba148-6839-4557-a8c7-afe402c1d5fa.mp4

**Comment by awoehrl** [comment]
Hi! I'm seeing the same problems. Latest version VSCode and SQLFluff extension.

**Comment by RobertOstermann** [comment]
This should be fixed in v0.0.6
