### ISSUE TITLE
When templater = "dbt" extension does not work

### ISSUE THREAD

**Issue by tekumara** [sqlfluff/vscode-sqlfluff#41]
When `templater = "dbt"` no linting occurs and Format Document shows the "SQLFluff is formatting the file" popup but nothing happens.

When `templater = "jinja"` it works.

sqlfluff                 0.8.1
sqlfluff-templater-dbt   0.8.1

**Comment by tnightengale** [comment]
Related to #27 and #38 

... Would be wonderful if a TS ninja with a passion for dbt could save us from this *almost* great extension 🙏

**Comment by tekumara** [comment]
@tnightengale it appears to respect .sqlfluff because when i change it to `templater = "jinja"` the extension works.

**Comment by courentin** [comment]
It seems that sqlfluff [does not support stdin](https://github.com/sqlfluff/sqlfluff/blob/e0c71c4ad0de314b218ffe5d6686d024b24a6bcb/plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py#L381-L384) with dbt templater, which can be the cause of this issue

**Comment by dcastillo-tab** [comment]
I'm having same issue

**Comment by RobertOstermann** [comment]
This has been fixed (sort of) in v0.0.6. The README contains the settings needed for the dbt templater to work.

**Comment by tanzaho** [comment]
Any idea if there should be specific Windows settings? 
My colleagues on Mac can have it working iwthout any problem, but those on Windows still have no items listed in the "Problems" screen.

**Comment by RobertOstermann** [comment]
There should not need to be any Windows specific settings.

If you run the sqlfluff lint from the command line does that work?
What specific settings do you have for the extension in the settings.json file?

**Comment by tanzaho** [comment]
> There should not need to be any Windows specific settings.
> 
> If you run the sqlfluff lint from the command line does that work? What specific settings do you have for the extension in the settings.json file?

I'll follow-up under another issue that seems more appropriate to Windows.

**Comment by simpl1g** [comment]
Hi, I'm trying to run with `v0.1.2` version and I receive. Is it connected issue?
```
WARNING File /workspaces/dbt_project/stdin was not found in dbt project
```

**Comment by RobertOstermann** [comment]
@simpl1g Were you seeing this problem in previous versions? Does this warning cause problems with linting/formatting? If so could you create a new issue for this?

**Comment by simpl1g** [comment]
@RobertOstermann thank you for reply, I was able to solve issue by rebuilding container

**Comment by benney-au-le** [comment]
I'm getting this warning too.
I followed the readme and I added this to my configuration.
```json
{
  "sqlfluff.linter.run": "onSave",
  "sqlfluff.experimental.format.executeInTerminal": true,
  "sqlfluff.format.enabled": true
}
```
I still get this warning
```
WARNING File /workspaces/dbt_project/stdin was not found in dbt project
```

**Comment by sudo-pradip** [comment]
I also getting same error 
```
WARNING    File /home/pdip/dbt-projects/airlinedemo_dbt/dags/dbt/airlinedemo/stdin was not found in dbt project 

```
when i set
```
[sqlfluff:templater:dbt]
project_dir = /home/pdip/dbt-projects/airlinedemo_dbt/dags/dbt/airlinedemo
```
