### ISSUE TITLE
Support native VS Code "format" capability to run "fix" in SQLFLuff

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/vscode-sqlfluff#6]
Hello!

Would it be possible to add autoformat (aka 'fix') support to this extension? I've created a hacky workaround (which I'll describe below), but native support would be so much more intuitive, powerful, and stable.

------------------
**Workaround**
------------------

1. Install the [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extension by **emeraldwalk**.

2. Add the snippet to `.vscode/settings.json`:

```json
{
    "emeraldwalk.runonsave": {
        "commands": [{
            "match": "\\.sql$",
            "cmd": "sqlfluff fix ${file} --force --rules L003,L009,L010,L011,L016,L30 --dialect snowflake"
        }]
    }
}
```

Caveats/issues that would be resolved by native format (fix) support:

 - You have to disable any competing "format on save" options for sql files.
 - Because saving happens in the background, there's a delay between saving and refresh. Occasionally you will receive "file modified externally" conflicts and be prompted to refresh and lose all changes or "overwrite" the external changes.
 - You could use explicit "format" option in VS Code natively and on-demand.
 - You can optionally enable "format on save" native option in VS Code.

------------------

Lastly, thanks so much for creating this extension. Having SQLFluff support in VS Code has been a gamechanger for our data team.

**Comment by alanmcruickshank** [comment]
I'm very up for extending the core sqlfluff library to support this kind of functionality, the work I've been doing on the sqlfluff api (on master but not released yet), should provide a basis for this.

@dorzey , do you know what kind of response you would need from the `sqlfluff` library to support this feature? If you can lay out a rough idea of how you'd want to interact with `sqlfluff` to do that then I'm happy to team up on making sure we have the right elements in the public API.

**Comment by dorzey** [comment]
@alanmcruickshank I'm not sure. I'll have to dig into the VSCode API docs. I'm still unfamiliar with the sqlfluff codebase; can you link me to a good starting point for the API work you mentioned?

**Comment by dorzey** [comment]
So we can provide this functionality via [CodeActions](https://code.visualstudio.com/api/references/vscode-api#CodeAction). There is a mechanism to link the CodeAction to the [Diagnostic](https://code.visualstudio.com/api/references/vscode-api#Diagnostic).

Given my understanding of how the sqlfluff fix commands works then at the moment we could:
* fix all errors in the file for all rules
* fix all errors in the file for a single rule

But we could not:
* fix a single error for a single rule

**Comment by aaronsteers** [comment]
While code actions integration is certainly valuable, it looks like this is a little different from the format, and (importantly) looks like a lot of work, since the expectation with code actions is to make a single atomic change.

I'm not adept at CS Code extensions myself, but I believe this is the integration point I was thinking of in this request: https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting

---------

The way I see the option in VS Code is "Format Document" in the command pallette:

![image](https://user-images.githubusercontent.com/18150651/100393838-e2946f80-2fef-11eb-8c2e-ab226984050e.png)

...which corresponds to this "Format on Save" option in VS Code settings:

![image](https://user-images.githubusercontent.com/18150651/100393880-09eb3c80-2ff0-11eb-8458-72faad4669c4.png)


---------

`registerDocumentFormattingEditProvider`: https://code.visualstudio.com/api/references/vscode-api#languages.registerDocumentFormattingEditProvider

![image](https://user-images.githubusercontent.com/18150651/100393663-479b9580-2fef-11eb-8340-3f152ed47c2d.png)

---------

This link was related to LSP (language server protocol) and looks like it may also be related:

https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting

![image](https://user-images.githubusercontent.com/18150651/100393751-99442000-2fef-11eb-80cb-559daefd314a.png)

**Comment by dorzey** [comment]
@aaronsteers still learning the VS Cdoe Extensions API myself; I wasn't aware of this extension point. I'll try and take a look.

I think going the LSP adds an extra layer of complexity and is probably only worth it if we wanted consolidated logic across a VS Code and Atom extension.

**Comment by aaronsteers** [comment]
Yeah, that makes sense. And I'm definitely still only beginning the learn this stuff myself. My understanding is that this integration point should still be completely workable without going the LSP route.

**Comment by dorzey** [comment]
Yep. I've not found anything yet that definitely requires the LSP
