### ISSUE TITLE
Change the severity of the linting issues.

### ISSUE THREAD

**Issue by Luttik** [sqlfluff/vscode-sqlfluff#66]
Currently, the severity of the SQLfluff linting issues are at the severity level `Error` this seems to be hardcoded [here](https://github.com/sqlfluff/vscode-sqlfluff/blob/master/src/features/linter.ts#L55). However, these linting issues are very unlikely to actually be an error. Instead, this should probably be `hint` or `warning`. It would be great if you were able to select this in the settings.

**Comment by RobertOstermann** [comment]
@Luttik In v0.1.5 I have added the option `sqlfluff.linter.diagnosticSeverity` and `sqlfluff.linter.diagnosticSeverityByRule` that allows you to set the default diagnostic severity and the severity for each rule.
