### ISSUE TITLE
Linted line numbers (squigly locations) are sometimes one too low

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/vscode-sqlfluff#7]
I sometimes see linted messages (the squigly locations) one line lower than they should be placed in the code. Is this something anyone else is experiencing, and is there anything we can do to resolve?

**Comment by aaronsteers** [comment]
Screenshots added for documentation:
![image](https://user-images.githubusercontent.com/18150651/97901128-9146d800-1cf0-11eb-833b-dec5223d2ae2.png)

![image](https://user-images.githubusercontent.com/18150651/97901148-999f1300-1cf0-11eb-969c-6d01240884f0.png)

**Comment by dorzey** [comment]
@aaronsteers could you please provide a full example of where you see the mismatch? Thanks!

**Comment by dorzey** [comment]
@aaronsteers this should now be fixed in 0.0.4
