### ISSUE TITLE
Version 0.1.6: Option to disable linting all files

### ISSUE THREAD

**Issue by alexeyegorov** [sqlfluff/vscode-sqlfluff#70]
Hello,
I was unaware of the change in the newest version 0.1.6 that re-lints everything in the project. In our setup we have more than 800 models already and linting all of them is not the right idea. Was there a reason to add this "feature"? Can you think of a setting that can disable this behaviour in the next versions?

**Comment by m0h318** [comment]
Hey, thanks for the awesome work you've done!

+1 on this.

I have the same issue here and it's over overloading my computer and vscode. 
Over 3k problems are listed (from compiled dbt models and others).

**Comment by RobertOstermann** [comment]
@alexeyegorov @m0h318 Sorry about those changes, probably should have thought through it more before just adding it. I have added a new configuration option, `sqlfluff.linter.lintEntireProject`, that defaults to `false` in version 0.1.7.

**Comment by alexeyegorov** [comment]
@m0h318 I was also wondering what settings did I just change!? :) @RobertOstermann Really great work and thanks for the quick response. I would have submitted a PR, but I didn't have a time to look into the code.
