### ISSUE TITLE
Linting all files consumes too much CPU

### ISSUE THREAD

**Issue by jivanpal** [sqlfluff/vscode-sqlfluff#71]
Hello, thanks for the extension! Unfortunately, as of v0.1.6, my computer has been pegged at 100% CPU because it wants to lint all my files, and since I am working on a large project (about 15 MB of SQL, 200k+ lines of code), this takes a very, very long time to run and brings my computer grinding to a halt.

Please could an option to disable this feature be added as a hotfix? After that, please consider adding the ability to configure the CPU-hungriness of this task when it is enabled, e.g. by assigning a maximum numbers of CPU cores, maximum number of concurrent sqlfluff processes, a process "niceness" level, etc.

Additionally, I have noticed that some sqlfluff processes linger even after VSCode has been quit.

System info:
- OS: macOS 10.15.7
- VSCode version: 1.72.2 (commit d045a5eda657f4d7b676dedbfa7aab8207f8a075)
- vscode-sqlfluff version: 0.1.7

**Comment by RobertOstermann** [comment]
@jivanpal Please upgrade to v0.1.7 and the linting entire project is turned off by default in that version.

**Comment by jivanpal** [comment]
@RobertOstermann Ah, thanks, seems that VSCode was actually stuck on 0.1.6 and needed a reload to put 0.1.7 into action! I'd be grateful if you could add some configuration options like I described, and perhaps keeping an internal record of which files were recently linted to prvent unnecessarily running them through sqlfluff again, as linting all files does still seem useful.
