### ISSUE TITLE
Diagnostic severity as "warning" for linting rules and "error" for parsing errors

### ISSUE THREAD

**Issue by Jonathan-MW** [sqlfluff/vscode-sqlfluff#76]
Would be nice to see yellow squigly lines for linting rule violations and red squigly lines for parsing errors by default. The only way I can currently make this work is by defining the diagnostic severity for each rule seperately in the settings, like:

```
"sqlfluff.linter.diagnosticSeverityByRule": [
        {
          "rule": "L001",
          "severity": "warning"
        },
        {
          "rule": "L002",
          "severity": "warning"
        },
       etc..........
      ],
```

Each rule has a group tag, see: https://docs.sqlfluff.com/en/stable/rules.html#module-sqlfluff.rules
Maybe we can somehow use the tag: "all"?

**Comment by RobertOstermann** [comment]
@Jonathan-MW You can change the setting `sqlfluff.linter.diagnosticSeverity` to adjust the default to `warning` instead of `error`. Then change the `sqlfluff.linter.diagnosticSeverityByRule` to alter the parsing errors to be red `error` problems instead of warnings.

```json
"sqlfluff.linter.diagnosticSeverity": "warning",
"sqlfluff.linter.diagnosticSeverityByRule": [
    {
      "rule": "PRS",
      "severity": "error"
    }
  ],
```

**Comment by Jonathan-MW** [comment]
Thanks! 
I also found that some extra linting rules need to be defined with severity: "error". 
E.g. [L038](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L038), as a comma after the last column definition in a select statement does throw an error for my sql engine (Databricks/spark sql). However Sqlfluff it does not throw an "unparsable" error for this trailing comma, even though the sql dialect is set to "databricks" in the vscode settings ("sqlfluff.dialect": "databricks").
