### ISSUE TITLE
How to set rule in settings.json config from .vscode?

### ISSUE THREAD

**Issue by CarlosSLoureiro** [sqlfluff/vscode-sqlfluff#79]
I need to set the `require_final_semicolon` as `true` for rule **L052** but I need to do it in the `settings.json` from `.vscode` folder. But I don't found any schema or example about how to make to set specific rules in `"sqlfluff.rules": []`.

**Comment by hblauth** [comment]
@CarlosSLoureiro How did you do this? I am also struggling here 😩

**Comment by CarlosSLoureiro** [comment]
@hblauth I have solved my problems doing from this way in my repository:

**.vscode/extensions.json**
```
{
    "recommendations": [
        "dorzey.vscode-sqlfluff"
    ]
}
```

**.vscode/settings.json**
```
{
    "sqlfluff.config": ".sqlfluff",
    "sqlfluff.dialect": "mysql",
    "sqlfluff.linter.run": "onType",
    "sqlfluff.suppressNotifications": true,
    "sqlfluff.executablePath": "sqlfluff",
    "sqlfluff.ignoreLocalConfig": false,
    "sqlfluff.ignoreParsing": false,
    "sqlfluff.rules": [],
    "sqlfluff.linter.arguments": [],
    "sqlfluff.linter.diagnosticSeverity": "error",
    "sqlfluff.linter.lintEntireProject": true,
    "sqlfluff.format.enabled": true
}
```

**.sqlfluff** (in repository root directory)
```
[sqlfluff]
dialect = mysql
exclude_rules = L001
max_line_length = 999

[sqlfluff:rules:convention.terminator]
require_final_semicolon = True
```

I'm using MacOS on Mac M1 and I'm not sure if it happens only in my platform. But if I try to follow their readme example (setting `sqlfluff.config` in **.vscode/settings.json** as `${workspaceFolder}/.sqlfluff`) it doesn't work here. I must not use **workspaceFolder**...
