### ISSUE TITLE
Add extension to Open VSX

### ISSUE THREAD

**Issue by harmtemolder** [sqlfluff/vscode-sqlfluff#80]
Some of us use alternatives to VS Code. (I use [VSCodium](https://github.com/VSCodium/vscodium) myself.) These don't have access to Microsoft's Visual Studio Marketplace. Of course we can download the `vsix` file from here and install it. But I feel that adding your extension to the open marketplace, [Open VSX](https://open-vsx.org/), will help you reach more coders.

**Comment by RobertOstermann** [comment]
Still working on verifying my ownership of the namespace, but here is a link to the extension on open-vsix.
https://open-vsx.org/extension/sqlfluff/vscode-sqlfluff

**Comment by harmtemolder** [comment]
Wow, that was fast, thanks!

**Comment by Vinfall** [comment]
Hi, I was wondering why there are two extensions on Open VSX and it's more confusing given that both are verified:
- https://open-vsx.org/extension/RobertOstermann/vscode-sqlfluff
- https://open-vsx.org/extension/sqlfluff/vscode-sqlfluff

As the first one matches your username, I assume it's the updated one. However, I'm a bit hesitated to install as the version looks _off_:
- sqlfluff.vscode-sqlfluff, 2.3.1, 2023-05-10
- RobertOstermann.vscode-sqlfluff, 3.2.0, 2024-08-20
- Latest GitHub release, 3.0.0, 2024-03-13
- Latest commit, 3.3.1, 2025-01-29

Also, maybe you can update the link in README to avoid future confusion.

**Comment by RobertOstermann** [comment]
Apologies for the mess that is the open vsx extension setup. I updated both the extensions.

**Comment by Vinfall** [comment]
Thanks for the update!

Meanwhile... there is now [a third extension](https://open-vsx.org/extension/dorzey/vscode-sqlfluff)🤯. In case you don't know yet, you can [deprecate extensions](https://github.com/EclipseFdn/open-vsx.org/wiki/Managing-Extensions#deprecating-an-extension) and (optionally) make it not downloadable or point it to another one (this makes more sense). You can deprecate the others and point them to sqlfluff.vscode-sqlfluff.
