### ISSUE TITLE
VSCode not highlighting linter errors

### ISSUE THREAD

**Issue by petertheguy** [sqlfluff/vscode-sqlfluff#86]
When using the sqlfluff extension in vscode (v2.2.4), I don't see any linting violations highlighted in my code even though I expect violations based on the .sqlfluff configuration. When using sqlfluff in the CLI (`sqlfluff lint`), I see all expected violations being flagged.

I'm using `templater = dbt` and `dialect = tsql`. I have the extension set to run the linter on save (as mentioned in the extension config). I have the following settings also configured in an attempt to force resolve this issue, but to no avail:

<img width="560" alt="Screenshot 2023-03-02 at 16 46 59" src="https://user-images.githubusercontent.com/124871287/222477974-89fec52c-9fb9-4a9b-acb9-898c418c2a5f.png">

<img width="762" alt="Screenshot 2023-03-02 at 16 47 07" src="https://user-images.githubusercontent.com/124871287/222478014-da4c4fe6-0432-4a43-a68e-088d11f7cd11.png">

Am I missing something obvious here?

**Comment by RobertOstermann** [comment]
@petertheguy Were you using this extension before v2.2.4 and if so was it working for you? I don't see anything obvious wrong with your setup, but perhaps the config file is not for the correct path? Even so, I would have expected it to work with the ignore local config unchecked.

You could check the output tab for the SQLFluff channel and see if it is executing the command you would expect it to and is showing the correct violations. That would help determine if it is a setup issue or if the extension is not correctly adding the problems to VSCode.

**Comment by petertheguy** [comment]
@RobertOstermann thanks for the suggestion. I'm not entirely certain if the extension worked before v2.2.4 as I had a conflicting linter, dbt-formatter, that I just uninstalled a couple of days ago. This is the output I originally received:

<img width="1350" alt="Screenshot 2023-03-03 at 09 06 55" src="https://user-images.githubusercontent.com/124871287/222666388-564e779c-bbb4-4861-b4bb-fddef0db335b.png">

So clearly the extension didn't know where to find the config file, so I provided it with the absolute path to where the config is saved. THis is the output this time:

<img width="1469" alt="Screenshot 2023-03-03 at 09 07 24" src="https://user-images.githubusercontent.com/124871287/222666629-d7644c85-4aa9-484a-8056-0432bad11ea5.png">


This feels like a step in the right direction, but the extension is still not flagging things as expected. Here is the output from the CLI for the same file as the screenshots above:

<img width="954" alt="Screenshot 2023-03-03 at 09 12 20" src="https://user-images.githubusercontent.com/124871287/222666961-33a096d7-a391-439a-8880-64ce882eacfa.png">

**Comment by petertheguy** [comment]
@RobertOstermann I just tested making all rules failures instead of warnings in the .sqlfluff config and that seems to have been the last piece of the puzzle:

<img width="1845" alt="Screenshot 2023-03-03 at 09 42 03" src="https://user-images.githubusercontent.com/124871287/222673177-fc145349-ceb5-4adf-8261-3d7b3099967a.png">

<img width="621" alt="Screenshot 2023-03-03 at 09 42 39" src="https://user-images.githubusercontent.com/124871287/222673339-ea6f6319-294d-4774-81ee-ac724231090d.png">


Thank for the suggestions, I'll go ahead and close this.
