### ISSUE TITLE
Linting the wrong file

### ISSUE THREAD

**Issue by ferdyh** [sqlfluff/vscode-sqlfluff#88]
When I run the linter (jinja or dbt) on a project file, the right command is executed, with the right relative path. However, when the command finishes the wrong file is linted. So for example:

models/datamart_a/model.sql (file i created and is used while executing sqlfluff)
target/compiled/projectname/models/datamart_a/model.sql (is linted / shown in Problems tab)

Can't seem to find any setting relating to this problem.

**Comment by alanmcruickshank** [comment]
Can you confirm whether this is just an issue of displaying the wrong file name, or whether you're getting unexpected linting errors as a result?

In the background the dbt templater does use the compiled file as part of the input, so I'm not totally suprised that this is happening. It definitely should _not_ be happening if you're using the jinja templater however.

**Comment by ferdyh** [comment]
When I open the file in the target folder (the one that actually linted), then most of the linting is in the wrong place. It takes a few seconds while sqlfluff is run on the file in the target folder and everything is in order again. So, to answer your question, yes, unexpected linting errors.

**Comment by RobertOstermann** [comment]
@ferdyh I believe you are correct. I struggled to recreate this unless I switched to the other file while the linting was being processed, which was weird. Either way, definitely a bug. Should be fixed later today in the next version

**Comment by RobertOstermann** [comment]
@ferdyh Please update to v2.2.5 and let us know if that solves the issue.

**Comment by ferdyh** [comment]
@RobertOstermann That looks better, thanks!
