### ISSUE TITLE
windows vscode:  sqlfluff executable was not found

### ISSUE THREAD

**Issue by skaylie** [sqlfluff/vscode-sqlfluff#95]
i have tried multiple ways to make this work, but the vscode extension cannot find the sqlfluff executable.  i have installed python and pip and sqlfluff on my windows machine and updated the Executable Path setting to "sqlfluff.executablePath": "C\\Users\\{my_dir}\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\sqlfluff.exe", which exists and executes.  i have added the same to my PATH, as well as the parent Scripts directory.  i have rebooted my machine to make sure all settings take effect.  

nothing is working.  i get the following error no matter what i've tried.  The sqlfluff executable was not found. Use the 'Executable Path' setting to configure the location of the executable, or add it to your PATH.

why isn't there a file selector dialog for this setting instead of having to enter it in text?  seems like that would be way easier.

**Comment by RobertOstermann** [comment]
Try changing the `sqlfluff.executablePath` setting to use forward slashes `/` instead of back slashes. Or perhaps try escaping your backslashes (double backslash) `\\`

If that doesn't work, are you able to run the `sqlfluff --version` command in a terminal successfully? If so I would expect the extension to work, if not then perhaps it is not added to your PATH correctly.

**Comment by skaylie** [comment]
thank you @RobertOstermann for the reply.  i still am not having any luck.  i have tried forward slashes and escaped backslashes.  i have tried configuring it to point at both the windows exe file and the wsl sqlfluff file.  `sqlfluff --version` runs correctly in cmd.  `where sqlfluff` points to the same directory and executable in my PATH and in `sqlfluff.executablePath`

**Comment by RobertOstermann** [comment]
@skaylie  Hmm, you mentioned wsl, is that what you are using? I haven't tested this extension using wsl before so not sure the exact steps to take. You could try looking at the SQLFluff output channel and seeing exactly what command is being run and perhaps that will help, but I would guess it would not help much.

It is also possible that this error is not a problem with the `executablePath`, but rather an issue with the `workingDirectory` not existing.

**Comment by qbatten** [comment]
Ope I think I figured it out. `workingDirectory` wants the absolute path to the workingdir, not the relative. That seems to have fixed it for me.

**Comment by skaylie** [comment]
great @qbatten!  i'm still not having any luck.  can you post the settings.json file sqlfluff sections in their entirety?  it'd be helpful to see if I need to use C:\..., /c/..., or \\wsl$... notation.

**Comment by qbatten** [comment]
@skaylie I'm on a mac; ran into same issue and resolved it by switching to full path. But not sure what the right windows-y path syntax is, sorry!

**Comment by skaylie** [comment]
this is very frustrating as i still get the same error:  "The sqlfluff executable was not found. Use the 'Executable Path' setting to configure the location of the executable, or add it to your PATH."

Is there anyone working on a windows machine that's gotten the vscode plugin to work?  **Can someone please post a CONCRETE EXAMPLE of what the inputs are supposed to look like to input the path to the executable.**

**Comment by RobertOstermann** [comment]
@skaylie Just to confirm, you are on a Windows machine, but working in WSL? When you open VSCode, are you in a workspace or just opening individual files? Can you post an example of what your `"sqlfluff.executablePath"` and `"sqlfluff.workingDirectory"` settings are? What do you see in the `sqlfluff` output channel within VSCode?

I don't have a concrete example for the settings as I have not tried this extension using WSL before. But I should have some time within the next few days to set it up and hopefully give you an example.

**Comment by skaylie** [comment]
thank you @RobertOstermann!!!  i appreciate the help.  i think this extension could save a lot of time for me over manually linting from the command line, which can be excruciating!.

- i'm in a workspace within my wsl tree:  /home/kaylies/code/mdc-data-etl-mwaa/
- i don't know what the sqlfluff output channel is?  how do i find it?
- here are some of the settings i've tried.  it's not an exhaustive list, since it's been a little while since i tried in earnest and i don't recall all of the permutations.  i tried these with forward slashes, back slashes, double back slashes, etc.:

executable path:
```
sqlfluff
/home/kaylies/.pyenv/shims/sqlfluff
\\wsl$\Ubuntu\home\kaylies\.pyenv\shims\sqlfluff
C:\Users\kaylies\AppData\Local\Programs\Python\Python311\Scripts\sqlfluff.exe
```

workingDirectory:
```
/home/kaylies/code/mdc-data-etl-mwaa/
\\wsl$\Ubuntu\home\kaylies\code\mdc-data-etl-mwaa
```

**Comment by RobertOstermann** [comment]
@skaylie 

This is where the output channel is.
![image](https://github.com/sqlfluff/vscode-sqlfluff/assets/46828475/e6cddc3a-d5a7-40f4-8807-69e48b1b0c18)

Here is what I have found so far for the path in WSL.

For the executable path, this is what worked for me with the WSL path. It was just the path I got from the `which sqlfluff` command. I think you mentioned you tried that and it didn't work, maybe something to do with it being in pyenv? I also was able to get it to work without setting an executable path, but had to have the sqlfluff command working in my default vscode terminal.

```
"sqlfluff.executablePath": "/home/username/.local/bin//sqlfluff"
```

If that doesn't work for you, I think you might have better luck with using the windows path, which should look something like this I think.
```
"sqlfluff.executablePath": "/mnt/c/Users/kaylies/AppData/Local/Programs/Python/Python311/Scripts/sqlfluff.exe"
```

I would recommend not setting the workingDirectory, though you could try `"sqlfluff.workingDirectory": "${fileDirname}"`, I had that setup and it worked for me.

Let me know if these changes work for you, if not I will try to investigate further, but am running out of ideas.

**Comment by skaylie** [comment]
hi @RobertOstermann.  sorry for the delayed response.  none of these solutions work for me.  i always get the same error that it can't find the executable.

i'm a bit surprised that i'm the only person experiencing this.  are there any users with windows machines that have the extension working in vscode?

**Comment by RobertOstermann** [comment]
@skaylie I am about out of ideas to solve your problem. I was able to get this working on a windows machine both with and without using WSL.

If you update to v2.3.4 there is a new command `SQLFluff Debug Extension` in the command palette that you could try to run. It will run through a few test commands to try and help narrow down if your actual issue is with the `workingDirectory` or the `executablePath` setting. Let me know where that test fails for you, maybe it will help solve the issue?

Beyond that, I am not sure what else to do. You could also clone this repo yourself and try debugging and seeing if you can get it working on your own. The code that spawns the child process is in `src/features/providers/sqlfluff.ts` around line `119`.

**Comment by skaylie** [comment]
@RobertOstermann are you able to post the exact entries for Executable Path in both basic windows and wsl?  maybe ( or likely!) there's something stupid i'm doing.

**Comment by RobertOstermann** [comment]
I don't think that will help much, I basically already posted them, and I usually just don't set anything for either of the settings and it just works. Like I mentioned in my previous comment, I think you'll have to try that debug command or clone the extension and try to debug it yourself.

WSL - Using SQLFluff on Linux

```json
"sqlfluff.executablePath": "/home/username/.local/bin//sqlfluff",
"sqlfluff.workingDirectory": "${fileDirname}",
```


WSL - Using SQLFluff on Windows

```json
"sqlfluff.executablePath": "/mnt/c/Users/username/AppData/Local/Programs/Python/Python39/Scripts/sqlfluff.exe",
"sqlfluff.workingDirectory": "${fileDirname}",
```

Windows
```json
"sqlfluff.executablePath": "sqlfluff",
"sqlfluff.workingDirectory": "${fileDirname}",
```

**Comment by skaylie** [comment]
@RobertOstermann I GOT IT TO WORK!!!!!!!!!🥳🥳🥳

the problem was with the working directory, not the executable path.  (you might want to revamp the 'can't find the executable' message to distinguish if it's having an issue with the executable path or the working directory.  also, you could enhance the message to show the fully qualified path it's looking for the executable in.)

thank you for the recommendation for the SQLFluff Debug Extension - that's what pointed me in the right direction.  it was looking for my \\$wsl folder, which didn't work.  it needed a fully qualified windows path, which for Ubuntu is buried deep in the Users directory.  

below are the exact inputs that work for me.  all settings are identical in both User and Workspace.

thank you for all the help!  this will save me a ton of time linting my files!



Executable Path:
sqlfluff

Working Directory
C:\Users\kaylies\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\kaylies\code\mdc-data-etl-mwaa

Config:
C:\Users\kaylies\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\kaylies\code\mdc-data-etl-mwaa\dags\dbt\.sqlfluff

**Comment by RobertOstermann** [comment]
Awesome! Glad you got it working! I definitely need to update the error message to note that it could be either executable path or working directory. And glad the new SQLFluff Debug Extension command helped point you in the right direction, wasn't sure if that would do the trick or not.
