### ISSUE TITLE
Note in workingDirectory setting description that it needs to be an absolute path

### ISSUE THREAD

**Issue by qbatten** [sqlfluff/vscode-sqlfluff#98]
See #95, [here](https://github.com/sqlfluff/vscode-sqlfluff/issues/95#issuecomment-1538637078).

**Comment by skaylie** [comment]
this is very frustrating as i still get the same error:  "The sqlfluff executable was not found. Use the 'Executable Path' setting to configure the location of the executable, or add it to your PATH."

Is there anyone working on a windows machine that's gotten the vscode plugin to work?  Can someone please post a CONCRETE EXAMPLE of what the inputs are supposed to look like to input the path to the executable.
